// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV9zYnm2klAVMXoaaZqOyaT8PxEi346U',
    appId: '1:165884140184:web:94e4b42bf79d50892c4eed',
    messagingSenderId: '165884140184',
    projectId: 'seave-b6cdc',
    authDomain: 'seave-b6cdc.firebaseapp.com',
    storageBucket: 'seave-b6cdc.firebasestorage.app',
    measurementId: 'G-CNN4VK2QKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4CYf6aY7KfWIe6mAxgO_ckoW-v6MUsgE',
    appId: '1:165884140184:android:7f13e98711f79cb32c4eed',
    messagingSenderId: '165884140184',
    projectId: 'seave-b6cdc',
    storageBucket: 'seave-b6cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5qeDLu3fgr3vrTeTD92dJs5w5xcD6mxY',
    appId: '1:165884140184:ios:f59e243eda30237a2c4eed',
    messagingSenderId: '165884140184',
    projectId: 'seave-b6cdc',
    storageBucket: 'seave-b6cdc.firebasestorage.app',
    iosBundleId: 'com.example.seave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5qeDLu3fgr3vrTeTD92dJs5w5xcD6mxY',
    appId: '1:165884140184:ios:f59e243eda30237a2c4eed',
    messagingSenderId: '165884140184',
    projectId: 'seave-b6cdc',
    storageBucket: 'seave-b6cdc.firebasestorage.app',
    iosBundleId: 'com.example.seave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcV9zYnm2klAVMXoaaZqOyaT8PxEi346U',
    appId: '1:165884140184:web:0558551dba692a3d2c4eed',
    messagingSenderId: '165884140184',
    projectId: 'seave-b6cdc',
    authDomain: 'seave-b6cdc.firebaseapp.com',
    storageBucket: 'seave-b6cdc.firebasestorage.app',
    measurementId: 'G-063JKJC8CT',
  );
}
